version: '3.8'

services:
  web_2:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/scr/app_2/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=docker

volumes:
  postgres_data: